- name: Generate SSH key for Jenkins master if not exists
  ansible.builtin.openssh_keypair:
    path: /var/lib/jenkins/.ssh/id_rsa
    owner: jenkins
    group: jenkins
    mode: '0600'
  when: not lookup('file', '/var/lib/jenkins/.ssh/id_rsa', errors='ignore')

- name: Fetch public key from master
  slurp:
    src: /var/lib/jenkins/.ssh/id_rsa.pub
  register: jenkins_pub

- name: Add Jenkins master public key to agent authorized_keys
  delegate_to: "{{ item }}"
  ansible.builtin.authorized_key:
    user: ubuntu
    key: "{{ jenkins_pub['content'] | b64decode }}"
  with_items: "{{ groups['agents'] }}"
